services:
  db01:
    image: mariadb:10.6.14
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - data:/var/lib/mysql:rw
    command:
      - mariadbd
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  data:
